[package]
name = "hamcycle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
nalgebra = "0.32.1"
numpy = "0.18"
pyo3 = "0.18.1"
