[package]
name = "hamcycle"
version = "0.1.0"
edition = "2021"

[dependencies]
common_macros = "0.1.1"
fxhash = "0.2.1"
itertools = "0.10.5"
ndarray = "0.15.6"
rayon = "1.7.0"

[profile.release]
debug = true
lto = true
opt-level = 3
