[package]
name = "hamcycle"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.5"
ndarray = "0.15.6"
rand = "0.8.5"
rayon = "1.7.0"

[profile.release]
debug = true
lto = true
opt-level = 3
