use ndarray::Array2;
use std::collections::{HashMap, HashSet, VecDeque};

use crate::structs::cycle::Cycle;
use crate::structs::vector::{Vector3D, Vector2D};

pub type Adjacency = HashMap<u32, HashSet<u32>>;
pub type AdjC<'a> = [(u32, &'a [u32])];
pub type Bobbins = Vec<u32>;
pub type Count = usize;
pub type Done = HashSet<usize>;
pub type Edge = (u32, u32);
pub type Edges = HashSet<Edge>;
pub type EdgeAdjacency = HashMap<Edge, HashSet<Edge>>;
pub type Idx = usize;
pub type Idxs = Vec<Idx>;
pub type Loom = Vec<VecDeque<u32>>;
pub type Neighbors = HashSet<u32>;
pub type Node = u32;
pub type Nodes = HashSet<u32>;
pub type Path = Vec<u32>;
pub type Paths = Vec<Path>;
pub type Point = i32;
pub type Points = HashSet<Point>;
pub type Solution = Vec<u32>;
pub type Slice<'a> = &'a [u32];
pub type Spool = HashMap<u32, Array2<i32>>;
pub type ZlevelNodesMap = HashMap<Zlevel, Nodes>;
pub type Subtours = Vec<Vec<u32>>;
pub type Thread = VecDeque<u32>;
pub type V2d = [i32; 2];
pub type V2Slice<'a> = &'a [[i32; 2]];
pub type V3d = [i32; 3];
pub type V3Slice<'a> = &'a [[i32; 3]];
pub type Vectors2d = Vec<Vector2D>;
pub type Vectors3d = Vec<Vector3D>;
pub type Vert2d = (i32, i32);
pub type Vert2dd = Vec<Vert2d>;
pub type Vert3d = (i32, i32, i32);
pub type VertsC2 = [Vert2d];
pub type VertsC3 = [Vert3d];
pub type VertIdx<'a> = HashMap<&'a Vector3D, u32>;
pub type Verts2d = Vec<Vert2d>;
pub type WarpedLoom<'a> = HashMap<usize, &'a mut Cycle<'a>>;
pub type Warps = Vec<Vec<u32>>;
pub type Wefts = Vec<VecDeque<u32>>;
pub type Weights = HashMap<u32, i32>;
pub type Woven = Vec<usize>;
pub type Yarn = Array2<i32>;
pub type Zlevel = i32;
pub type ZOrder = Vec<(i32, usize)>;

